apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-global
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: global
type: Opaque
data:
  internal-identity-key: {{ .Values.global.internalIdentityKey | b64enc | quote }}
  duo-key: {{ .Values.global.duoKey | b64enc | quote }}
  installation-id: {{ .Values.global.duoKey | b64enc | quote }}
  installation-key: {{ .Values.global.installationId | b64enc | quote }}
  yubico-client-id: {{ .Values.global.yubicoClientId | b64enc | quote }}
  yubico-key: {{ .Values.global.yubicoKey | b64enc | quote }}
  mail-reply-to-email: {{ .Values.global.mail.replyToEmail | b64enc | quote }}
  mail-host: {{ .Values.global.mail.host | b64enc | quote }}
  mail-username: {{ .Values.global.mail.username | b64enc | quote }}
  mail-password: {{ .Values.global.mail.password | b64enc | quote }}
  mail-ssl: {{ .Values.global.mail.ssl | b64enc | quote }}
  mail-port: {{ .Values.global.mail.port | b64enc | quote }}
  mail-use-default-credentials: {{ .Values.global.mail.useDefaultCredentials | b64enc | quote }}
  disable-user-registration: {{ .Values.global.disableUserRegistration | b64enc | quote }}
  admins: {{ .Values.global.admins | b64enc | quote }}
