{{- if and .Values.mssql.enabled .Values.mssql.persistence.backups.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql-backups
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mssql
spec:
  accessModes:
    - {{ .Values.mssql.persistence.backups.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mssql.persistence.backups.size | quote }}
{{- if .Values.mssql.persistence.backups.storageClass }}
{{- if (eq "-" .Values.mssql.persistence.backups.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.mssql.persistence.backups.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
